export interface TechnologyDetector {
  name: string;
  slug: string;
  icon?: string;
  color?: string;
  files: string[];
  packageJsonKeys?: string[];
  fileExtensions?: string[];
}

export const TECHNOLOGY_DETECTORS: TechnologyDetector[] = [
  {
    name: 'JavaScript',
    slug: 'javascript',
    icon: 'javascript',
    color: '#F7DF1E',
    files: [],
    fileExtensions: ['.js', '.mjs', '.cjs'],
  },
  {
    name: 'TypeScript',
    slug: 'typescript',
    icon: 'typescript',
    color: '#3178C6',
    files: ['tsconfig.json'],
    fileExtensions: ['.ts', '.tsx'],
  },
  {
    name: 'Vue',
    slug: 'vue',
    icon: 'vue',
    color: '#42B883',
    files: [],
    packageJsonKeys: ['vue'],
    fileExtensions: ['.vue'],
  },
  {
    name: 'React',
    slug: 'react',
    icon: 'react',
    color: '#61DAFB',
    files: [],
    packageJsonKeys: ['react'],
    fileExtensions: ['.jsx', '.tsx'],
  },
  {
    name: 'Node.js',
    slug: 'nodejs',
    icon: 'nodejs',
    color: '#339933',
    files: ['package.json'],
  },
  {
    name: 'Next.js',
    slug: 'nextjs',
    icon: 'nextjs',
    color: '#000000',
    files: ['next.config.js', 'next.config.mjs', 'next.config.ts'],
    packageJsonKeys: ['next'],
  },
  {
    name: 'Nuxt',
    slug: 'nuxt',
    icon: 'nuxt',
    color: '#00DC82',
    files: ['nuxt.config.js', 'nuxt.config.ts'],
    packageJsonKeys: ['nuxt'],
  },
  {
    name: 'PHP',
    slug: 'php',
    icon: 'php',
    color: '#777BB4',
    files: ['composer.json'],
    fileExtensions: ['.php'],
  },
  {
    name: 'Laravel',
    slug: 'laravel',
    icon: 'laravel',
    color: '#FF2D20',
    files: ['artisan'],
    packageJsonKeys: ['laravel-mix', 'laravel-vite-plugin'],
  },
  {
    name: 'Python',
    slug: 'python',
    icon: 'python',
    color: '#3776AB',
    files: ['requirements.txt', 'pyproject.toml', 'setup.py'],
    fileExtensions: ['.py'],
  },
  {
    name: 'Django',
    slug: 'django',
    icon: 'django',
    color: '#092E20',
    files: ['manage.py'],
  },
  {
    name: 'Rust',
    slug: 'rust',
    icon: 'rust',
    color: '#000000',
    files: ['Cargo.toml'],
    fileExtensions: ['.rs'],
  },
  {
    name: 'Go',
    slug: 'go',
    icon: 'go',
    color: '#00ADD8',
    files: ['go.mod'],
    fileExtensions: ['.go'],
  },
  {
    name: 'CSS',
    slug: 'css',
    icon: 'css',
    color: '#1572B6',
    files: [],
    fileExtensions: ['.css'],
  },
  {
    name: 'SCSS',
    slug: 'scss',
    icon: 'sass',
    color: '#CC6699',
    files: [],
    fileExtensions: ['.scss', '.sass'],
  },
  {
    name: 'HTML',
    slug: 'html',
    icon: 'html',
    color: '#E34F26',
    files: [],
    fileExtensions: ['.html', '.htm'],
  },
  {
    name: 'Docker',
    slug: 'docker',
    icon: 'docker',
    color: '#2496ED',
    files: ['Dockerfile', 'docker-compose.yml', 'docker-compose.yaml'],
  },
  {
    name: 'Git',
    slug: 'git',
    icon: 'git',
    color: '#F05032',
    files: ['.git'],
  },
  {
    name: 'Vite',
    slug: 'vite',
    icon: 'vite',
    color: '#646CFF',
    files: ['vite.config.js', 'vite.config.ts', 'vite.config.mjs'],
    packageJsonKeys: ['vite'],
  },
  {
    name: 'Electron',
    slug: 'electron',
    icon: 'electron',
    color: '#47848F',
    files: [],
    packageJsonKeys: ['electron'],
  },
  {
    name: 'Tailwind CSS',
    slug: 'tailwindcss',
    icon: 'tailwindcss',
    color: '#06B6D4',
    files: ['tailwind.config.js', 'tailwind.config.ts'],
    packageJsonKeys: ['tailwindcss'],
  },
  {
    name: 'Java',
    slug: 'java',
    icon: 'java',
    color: '#007396',
    files: ['pom.xml', 'build.gradle', 'build.gradle.kts'],
    fileExtensions: ['.java'],
  },
  {
    name: 'Kotlin',
    slug: 'kotlin',
    icon: 'kotlin',
    color: '#7F52FF',
    files: ['build.gradle.kts'],
    fileExtensions: ['.kt', '.kts'],
  },
  {
    name: 'Android',
    slug: 'android',
    icon: 'android',
    color: '#3DDC84',
    files: ['AndroidManifest.xml', 'app/build.gradle', 'settings.gradle'],
  },
  {
    name: 'Swift',
    slug: 'swift',
    icon: 'swift',
    color: '#FA7343',
    files: ['Package.swift'],
    fileExtensions: ['.swift'],
  },
  {
    name: 'Objective-C',
    slug: 'objectivec',
    icon: 'objectivec',
    color: '#438EFF',
    files: [],
    fileExtensions: ['.m', '.mm', '.h'],
  },
  {
    name: 'iOS',
    slug: 'ios',
    icon: 'apple',
    color: '#000000',
    files: ['Info.plist', 'Podfile'],
  },
  {
    name: 'C#',
    slug: 'csharp',
    icon: 'csharp',
    color: '#239120',
    files: [],
    fileExtensions: ['.cs'],
  },
  {
    name: '.NET',
    slug: 'dotnet',
    icon: 'dotnet',
    color: '#512BD4',
    files: ['.csproj', '.sln', '.fsproj', '.vbproj'],
  },
  {
    name: 'Ruby',
    slug: 'ruby',
    icon: 'ruby',
    color: '#CC342D',
    files: ['Gemfile'],
    fileExtensions: ['.rb'],
  },
  {
    name: 'Ruby on Rails',
    slug: 'rails',
    icon: 'rails',
    color: '#CC0000',
    files: ['config/routes.rb', 'Rakefile'],
  },
  {
    name: 'C',
    slug: 'c',
    icon: 'c',
    color: '#A8B9CC',
    files: [],
    fileExtensions: ['.c', '.h'],
  },
  {
    name: 'C++',
    slug: 'cpp',
    icon: 'cpp',
    color: '#00599C',
    files: ['CMakeLists.txt'],
    fileExtensions: ['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx'],
  },
  {
    name: 'Flutter',
    slug: 'flutter',
    icon: 'flutter',
    color: '#02569B',
    files: ['pubspec.yaml'],
    packageJsonKeys: ['flutter'],
  },
  {
    name: 'Dart',
    slug: 'dart',
    icon: 'dart',
    color: '#0175C2',
    files: ['pubspec.yaml'],
    fileExtensions: ['.dart'],
  },
  {
    name: 'React Native',
    slug: 'reactnative',
    icon: 'react',
    color: '#61DAFB',
    files: ['app.json', 'metro.config.js'],
    packageJsonKeys: ['react-native'],
  },
  {
    name: 'Expo',
    slug: 'expo',
    icon: 'expo',
    color: '#000020',
    files: ['app.json'],
    packageJsonKeys: ['expo'],
  },
  // AI Coding Assistants
  {
    name: 'Claude Code',
    slug: 'claude-code',
    icon: 'anthropic',
    color: '#D97757',
    files: ['.claude', 'CLAUDE.md'],
  },
  {
    name: 'Beads',
    slug: 'beads',
    icon: 'beads',
    color: '#6366F1',
    files: ['.beads'],
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    icon: 'cursor',
    color: '#000000',
    files: ['.cursor', '.cursorrules'],
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    icon: 'github',
    color: '#000000',
    files: ['.github/copilot-instructions.md'],
  },
  // AI SDKs
  {
    name: 'Anthropic SDK',
    slug: 'anthropic-sdk',
    icon: 'anthropic',
    color: '#D97757',
    files: [],
    packageJsonKeys: ['@anthropic-ai/sdk'],
  },
  {
    name: 'OpenAI SDK',
    slug: 'openai-sdk',
    icon: 'openai',
    color: '#10A37F',
    files: [],
    packageJsonKeys: ['openai'],
  },
  {
    name: 'Vercel AI SDK',
    slug: 'vercel-ai-sdk',
    icon: 'vercel',
    color: '#000000',
    files: [],
    packageJsonKeys: ['ai'],
  },
];
